Build error response niceties
Will amongst other things copy the log file vie command with you favourite pager to the clipboard if you have pbcopy that is.

diff --git a/libexec/phpenv-install b/libexec/phpenv-install
--- a/libexec/phpenv-install
+++ b/libexec/phpenv-install
@@ -140,6 +140,7 @@ function list_releases() {
 # Handles build errors, and displays the last 10 line of the build log.
 function build_error() {
   {
+    [[ ${STATUS} -eq 0 ]] && echo "Aborting installation." && exit ${STATUS}
     echo
     echo "BUILD ERROR: STATUS is $STATUS"
     echo "The script aborted unexpectedly when a command returned a non zero exit code."
