Argument validation
Disallow Release or Build arguments that look like arguments.

It's no fun trying to delete a version folder called --release

diff --git a/libexec/phpenv-install b/libexec/phpenv-install
--- a/libexec/phpenv-install
+++ b/libexec/phpenv-install
@@ -517,6 +517,15 @@ fi
 if [[ "$3" = "-c" || "$3" = "--continue" ]]; then
   CONTINUE=${4}
 fi
+if [ "${RELEASE:0:1}" = '-' ]; then
+  log "Error" "Unknown option $RELEASE, expected release identifier, aborting."
+  exit 1
+fi
+if [ "${BUILD:0:1}" = '-' ]; then
+  log "Error" "Unknown option $BUILD, expected a build identifier, aborting."
+  exit 1
+fi
+
 # Generate the Path for the build log.
 LOG_PATH="/tmp/phpenv-install-$RELEASE.$(date "+%Y%m%d%H%M%S").log"
 # Redirect everything logged to STDOUT to the Log file.
