Update version-file-read to match upstream behavior
Ignore carriage returns
Prevent directory traversal
Disallow path segments

diff --git a/libexec/phpenv-version-file-read b/libexec/phpenv-version-file-read
--- a/libexec/phpenv-version-file-read
+++ b/libexec/phpenv-version-file-read
@@ -5,18 +5,14 @@ set -e
 
 VERSION_FILE="$1"
 
-if [ -e "$VERSION_FILE" ]; then
-  # Read the first non-whitespace word from the specified version file.
-  # Be careful not to load it whole in case there's something crazy in it.
-  version=""
-  while read -a words; do
-    word="${words[0]}"
-    if [ -z "$version" ] && [ -n "$word" ]; then
-      version="$word"
-    fi
-  done < <( cat "$VERSION_FILE" && echo )
+if [ -s "$VERSION_FILE" ]; then
+  # Read the first word from the specified version file. Avoid reading it whole.
+  IFS="${IFS}"$'\r'
+  read -n 1024 -d "" -r version _ <"$VERSION_FILE" || :
 
-  if [ -n "$version" ]; then
+  if [ "$version" = ".." ] || [[ $version == */* ]]; then
+    echo "phpenv: invalid version in \`$VERSION_FILE'" >&2
+  elif [ -n "$version" ]; then
     echo "$version"
     exit
   fi
