Update with change from latest (1.0.0) rbenv

diff --git a/libexec/phpenv-hooks b/libexec/phpenv-hooks
--- a/libexec/phpenv-hooks
+++ b/libexec/phpenv-hooks
@@ -9,6 +9,8 @@ set -e
 if [ "$1" = "--complete" ]; then
   echo exec
   echo rehash
+  echo version-name
+  echo version-origin
   echo which
   exit
 fi
@@ -24,29 +26,43 @@ fi
 #  PHPENV_COMMAND_HOOK="*"
 #fi
 
+if ! enable -f "${BASH_SOURCE%/*}"/phpenv-realpath.dylib realpath 2>/dev/null; then
+  if [ -n "$PHPENV_NATIVE_EXT" ]; then
+    echo "phpenv: failed to load \`realpath' builtin" >&2
+    exit 1
+  fi
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "phpenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
+
 resolve_link() {
-  $(type -p greadlink readlink | head -1) $1
+  $READLINK "$1"
 }
 
 realpath() {
-  local cwd="$(pwd)"
-  local base="$(basename $1)"
+  local cwd="$PWD"
   local path="$1"
+  local name
 
   while [ -n "$path" ]; do
-    cd "${path%/*}"
-    local name="${path##*/}"
+    name="${path##*/}"
+    [ "$name" = "$path" ] || cd "${path%/*}"
     path="$(resolve_link "$name" || true)"
   done
 
-  echo "$(pwd)/$base"
+  echo "${PWD}/$name"
   cd "$cwd"
 }
+fi
+
+IFS=: hook_paths=($PHPENV_HOOK_PATH)
 
 shopt -s nullglob
-for path in ${PHPENV_HOOK_PATH//:/$'\n'}; do
-  for script in $path/"$PHPENV_COMMAND"/*.bash; do
-    echo $(realpath $script)
+for path in "${hook_paths[@]}"; do
+  for script in "$path/$PHPENV_COMMAND"/*.bash; do
+    realpath "$script"
   done
 done
 #
diff --git a/libexec/phpenv-prefix b/libexec/phpenv-prefix
--- a/libexec/phpenv-prefix
+++ b/libexec/phpenv-prefix
@@ -22,10 +22,15 @@ elif [ -z "$PHPENV_VERSION" ]; then
 fi
 
 if [ "$PHPENV_VERSION" = "system" ]; then
-  PHP_PATH="$(phpenv-which php)"
-  PHP_PATH="${PHP_PATH%/*}"
-  echo "${PHP_PATH%/bin}"
-  exit
+  if PHP_PATH="$(phpenv-which php 2>/dev/null)"; then
+    PHP_PATH="${PHP_PATH%/*}"
+    PHPENV_PREFIX_PATH="${PHP_PATH%/bin}"
+    echo "${PHPENV_PREFIX_PATH:-/}"
+    exit
+  else
+    echo "phpenv: system version not found in PATH" >&2
+    exit 1
+  fi
 fi
 
 PHPENV_PREFIX_PATH="${PHPENV_ROOT}/versions/${PHPENV_VERSION}"
diff --git a/libexec/phpenv-versions b/libexec/phpenv-versions
--- a/libexec/phpenv-versions
+++ b/libexec/phpenv-versions
@@ -1,13 +1,69 @@
 #!/usr/bin/env bash
 # Summary: List all PHP versions available to phpenv
-# Usage: phpenv versions [--bare]
+# Usage: phpenv versions [--bare] [--skip-aliases]
 #
 # Lists all PHP versions found in `$PHPENV_ROOT/versions/*'.
 
 set -e
 [ -n "$PHPENV_DEBUG" ] && set -x
 
-if [ "$1" = "--bare" ]; then
+unset bare
+unset skip_aliases
+# Provide phpenv completions
+for arg; do
+  case "$arg" in
+  --complete )
+    echo --bare
+    echo --skip-aliases
+    exit ;;
+  --bare ) bare=1 ;;
+  --skip-aliases ) skip_aliases=1 ;;
+  * )
+    phpenv-help --usage versions >&2
+    exit 1
+    ;;
+  esac
+done
+
+versions_dir="${PHPENV_ROOT}/versions"
+
+if ! enable -f "${BASH_SOURCE%/*}"/phpenv-realpath.dylib realpath 2>/dev/null; then
+  if [ -n "$PHPENV_NATIVE_EXT" ]; then
+    echo "phpenv: failed to load \`realpath' builtin" >&2
+    exit 1
+  fi
+
+  READLINK=$(type -p greadlink readlink | head -1)
+  if [ -z "$READLINK" ]; then
+    echo "phpenv: cannot find readlink - are you missing GNU coreutils?" >&2
+    exit 1
+  fi
+
+  resolve_link() {
+    $READLINK "$1"
+  }
+
+  realpath() {
+    local cwd="$PWD"
+    local path="$1"
+    local name
+
+    while [ -n "$path" ]; do
+      name="${path##*/}"
+      [ "$name" = "$path" ] || cd "${path%/*}"
+      path="$(resolve_link "$name" || true)"
+    done
+
+    echo "${PWD}/$name"
+    cd "$cwd"
+  }
+fi
+
+if [ -d "$versions_dir" ]; then
+  versions_dir="$(realpath "$versions_dir")"
+fi
+
+if [ -n "$bare" ]; then
   hit_prefix=""
   miss_prefix=""
   current_version=""
@@ -19,12 +75,15 @@ else
   include_system="1"
 fi
 
+num_versions=0
+
 print_version() {
   if [ "$1" == "$current_version" ]; then
     echo "${hit_prefix}$(phpenv-version 2>/dev/null)"
   else
     echo "${miss_prefix}$1"
   fi
+  num_versions=$((num_versions + 1))
 }
 
 # Include "system" in the non-bare output, if it exists
@@ -32,8 +91,19 @@ if [ -n "$include_system" ] && PHPENV_VERSION=system phpenv-which php >/dev/null
   print_version system
 fi
 
-for path in "${PHPENV_ROOT}/versions/"*; do
+shopt -s nullglob
+for path in "$versions_dir"/*; do
   if [ -d "$path" ]; then
+    if [ -n "$skip_aliases" ] && [ -L "$path" ]; then
+      target="$(realpath "$path")"
+      [ "${target%/*}" != "$versions_dir" ] || continue
+    fi
     print_version "${path##*/}"
   fi
 done
+shopt -u nullglob
+
+if [ "$num_versions" -eq 0 ] && [ -n "$include_system" ]; then
+  echo "Warning: no PHP detected on the system" >&2
+  exit 1
+fi
